# Generated by Django 3.0.4 on 2020-03-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(default='')),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('content', models.TextField(default=' ')),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('content', models.TextField(default=' ')),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('content', models.TextField(default=' ')),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
