# Generated by Django 3.0.4 on 2020-03-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200321_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='img',
            field=models.ImageField(upload_to='static\\images'),
        ),
        migrations.AlterField(
            model_name='consumerlaw',
            name='img',
            field=models.ImageField(upload_to='static\\images'),
        ),
        migrations.AlterField(
            model_name='creditrepair',
            name='img',
            field=models.ImageField(upload_to='static\\images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(upload_to='static\\images'),
        ),
    ]
