# Generated by Django 5.0.1 on 2024-02-03 21:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200321_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='consumerlaw',
            options={'verbose_name_plural': 'Consumer Laws'},
        ),
        migrations.AlterModelOptions(
            name='creditrepair',
            options={'verbose_name_plural': 'Credit Repairs'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consumerlaw',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='consumerlaw',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='creditrepair',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='creditrepair',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=300),
        ),
    ]
