# Generated by Django 5.0.1 on 2024-02-04 15:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_aboutus_options_alter_consumerlaw_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='consumerlaw',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='creditrepair',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=500),
        ),
    ]
